"""databases table, added addresses fileds

Revision ID: ae5d71f4ed25
Revises: ee570032cc1c
Create Date: 2020-09-16 14:34:19.627675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae5d71f4ed25'
down_revision = 'ee570032cc1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('database', sa.Column('host_address', sa.String(length=64), nullable=True))
    op.add_column('database', sa.Column('jump_address', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_database_host_address'), 'database', ['host_address'], unique=True)
    op.create_index(op.f('ix_database_jump_address'), 'database', ['jump_address'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_database_jump_address'), table_name='database')
    op.drop_index(op.f('ix_database_host_address'), table_name='database')
    op.drop_column('database', 'jump_address')
    op.drop_column('database', 'host_address')
    # ### end Alembic commands ###
