"""users table, added roles

Revision ID: daa125133e83
Revises: e3402c506c45
Create Date: 2020-09-16 16:46:37.816441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'daa125133e83'
down_revision = 'e3402c506c45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('groups', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'groups')
    # ### end Alembic commands ###
